### PR TITLE
Add Ruby 3.1.0, remove Ruby 2.6

### PR DESCRIPTION
**Pull request by FooBarWidget**

### CODE REVIEW

**Comment by Envek** [comment]
Btw, why are you removing Ruby 2.6? It is still supported till end of March: https://www.ruby-lang.org/en/downloads/branches/

**Comment by FooBarWidget** [comment]
Having Ruby 2.6 in there puts too much strain on the CI/CD system. It would be more feasible once we have better caching (#86). But for now, and seeing that Ruby 2.6 only has 3 months to live, I think it's better to remove it.

Note that we're only removing *building* Ruby 2.6. Previously-published Ruby 2.6 packages remain in the repository and are still installable.

**Comment by FooBarWidget** [comment]
3.1 is now released. Enjoy!

**Comment by ollym** [comment]
@FooBarWidget is this built with the new yjit VM?

**Comment by bogn83** [comment]
Yes it is

**Comment by ollym** [comment]
Anyone done any tests to see how the patches in these builds (jemalloc / malloc_trim) interact with YJIT?

**Comment by FooBarWidget** [comment]
The automated tests haven't picked up any *problems* (like crashes) but other than that, no. We welcome any reports. :)

**Pull request merged**
