### PR TITLE
Upgrades Ruby to 3.0.2, 2.7.4, and 2.6.8 releases

### PR DESCRIPTION
**Pull request by san983**
New Ruby versions were just released:

- https://www.ruby-lang.org/en/news/2021/07/07/ruby-3-0-2-released/
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/
- https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-6-8-released/

### CODE REVIEW

**Comment by FooBarWidget** [comment]
Thanks for the pull request. Publishing is broken at the moment (#70). I plan on fixing that some time this week, after which I'll have a look at your pull request.

**Comment by ioki-klaus** [comment]
@FooBarWidget What are you suggesting for people that want to fix those CVEs and are using fullstaq ruby until then?

**Comment by FooBarWidget** [comment]
@ioki-klaus Package *publishing* is broken, but package *building* still works. People can [follow this guide](https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/blob/main/dev-handbook/building-packages-locally.md) to build their own packages locally.

**Comment by posiczko** [comment]
@FooBarWidget Is there anything we can do to help?

**Comment by FooBarWidget** [comment]
I'm almost done so there's not much to help with. I've spent a good chunk of this week working on the solution and I think I can launch it today.

But I would appreciate a review of the setup's technical documentation once I'm done.

**Comment by FooBarWidget** [comment]
CI/CD package publishing is now fixed, and this pull request is now being released.

Thanks @san983!

**Comment by FooBarWidget** [comment]
I would appreciate a review of the following document, which describes how our new APT/YUM repo setup and publication process works: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/blob/main/dev-handbook/apt-yum-repo.md

While conceptually simple, publishing APT/YUM repositories is actually riddled with many caveats. It's extremely non-trivial to set up a repository and a publishing process that's *reliable, highly available, consistent and plays well with CI/CD*. Special attention was given to the following problems:
- Atomic publishing
- Strong consistency
- Concurrency safe publishing
- Segregated, temporary repositories for testing
- Production data parity during testing
- Preservation of old package versions
- Optional overwrite protection
- Backups

**Pull request merged**
