### PR TITLE
Added centos 8 docker file and adapted config/workflows

### PR DESCRIPTION
**Pull request by wollistik**
Hi, I added a docker images and adapted the config files. The Docker image builds, but
unfortunately I could not test building the ruby packages, because I do not know how this works :-(
Could you please have a look over the changes and give me some feedback?

### CODE REVIEW

**Comment by wollistik** [comment]
I see a check is not working. This script wants to pull a centos image from google cloud and wants credentials for this. I do not have an account nor am I sure how to solve this. Can you please help?

**Comment by FooBarWidget** [comment]
Thanks for the contribution @wollistik! It looks like that part of the CI is broken. I'll get this fixed so that you can test properly.

**Comment by FooBarWidget** [comment]
It looks like the CI isn't broken. It's a Github problem: they [don't allow CI runs of pull requests to access secrets](https://github.community/t/allow-secrets-to-be-shared-with-forks-from-trusted-actions/16525), for security reasons. I'll make a new pull request so that the CI works.

**Comment by FooBarWidget** [comment]
The CI is now done. It's failing in the test jobs: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/runs/716370929?check_suite_focus=true

It looks like `yum makecache` (which we use to import the Fullstaq Ruby's repo GPG key) fails, but it doesn't tell us why. I'm also investigating this. What I've found so far is this:

 * It has got something to do with sudo. If we don't install sudo in the test container, then `yum makecache` succeeds.
 * It has got something to do with having a TTY or not. If I run this test locally, with a TTY enabled (`docker run -ti`), then `yum makecache` succeeds.
 * In CentOS 8, yum is now an alias for dnf. If I inspect the sudo package, then I see that the sudo package contains the config file /etc/dnf/protected.d/sudo.conf, which tells dnf to enable some undocumented 'sudo' mode. However, removing this file does not solve the problem.

**Comment by FooBarWidget** [comment]
@wollistik I managed to fix the aforementioned test problem by ignoring the 'yum makecache' error. I've committed my fix in the [feature/centos-8](https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/tree/feature/centos-8) branch. [Here is the CI result](https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/actions/runs/117880006).

Do you agree with my change and my suggestions? If so, please update your fork and I'll merge.

**Comment by wollistik** [comment]
@FooBarWidget thanks for looking so quickly at my pullrequest! I rebased onto your branch and mentioned CentOS 8  in the readme as you suggested. Do you want to squash all the commits?

**Comment by FooBarWidget** [comment]
All right, the pull request has been merged. Packages will be released as soon as the CI/CD on master completes.

**Comment by wollistik** [comment]
Thank you very much!

**Pull request merged**
