### PR TITLE
Upgrade Ruby 2.7 to 2.7.2 release

### PR DESCRIPTION
**Pull request by caius**
Ruby Core have released Ruby 2.7.2, and with a wave of excitement I'd like to help Fullstaq have this version available for all to install. https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

From looking at the instructions in `dev-handbook/add-new-ruby-version.md` I think these are the only config changes required to start building these packages.

(PS: This project is awesome, and I _love_ the included documentation. Really easy to get a sense of how it hangs together and works. Thank you very much for creating this project 👏.)

### CODE REVIEW

**Comment by caius** [comment]
Have followed the instructions for building packages locally, with .deb for Debian 9 (guess what I'm mostly using these packages on 😁) and then run the test scripts against the built package locally. Everything appears to work for me.

**Comment by FooBarWidget** [comment]
Thanks for the pull request! The CI is currently broken (see #60). I'm trying to fix it but Github is not making it easy for me (https://github.community/t/max-workflow-file-size/135445). I'm trying to fix this as quickly as I can.

**Comment by FooBarWidget** [comment]
By the way, your pull request does not include a regenerated Github Workflow file, probably because you did not set up the [Git hooks](https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/blob/main/dev-handbook/dev-environment-setup.md#git-hooks).

This is not a big problem because I can regenerate the workflow file for you (and I need to fix the CI first anyway) but maybe something to keep in mind for the future.

**Comment by caius** [comment]
> By the way, your pull request does not include a regenerated Github Workflow file

Whoops! I think I had committed this before running the configuration for the git hooks, apologies. I've re-committed and force pushed this branch so it has a regenerated workflow file in now!

**Comment by FooBarWidget** [comment]
I think I've solved #60, but I'm still running into what appears to be Github Actions workflow file limit. Progress can be tracked in #62.

**Comment by FooBarWidget** [comment]
The CI issues *should* be solved now. I'm resolving conflicts in your PR and testing it.

**Comment by FooBarWidget** [comment]
Merged and being released now. Thank you!

**Comment by caius** [comment]
@FooBarWidget Awesome, thank you for getting this through!

**Pull request closed without merging**
